### ISSUE TITLE
bgcolor not setting butbgcolor

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#8]
If bgcolor is set to white, butbgcolor value remains to be 808080 instead of ffffff.

**Comment by mfo13** [comment]
Well... that's because they are independent parameters. Do you really prefer that buttombgcolor follows bgcolor everytime this last one is changed? Imagine an user wants a pink buttombgcolor independent of bgcolor... everytime such user changes bgcolor the buttombgcolor needs to be set again. I understand the opposite is true, if an user wants both allways the same color thus everytime bgcolor is changed buttombgcolor must be set as well. Actually I think it is easy to make the script to work like this last example intead of the first one. Just tell me which one you think is more probable.

**Comment by bcube2** [comment]
> Do you really prefer that buttombgcolor follows bgcolor everytime this last one is changed?

Basically, for all my requests, I am asking to be consistent with the ACJS documentation. The other tool mentioned in the Parameters section may be taken as a reference, because as far as I know, it is consistent with the doc.

The doc for the butbgcolor parameter is saying "If this parameter is missing, the color of the buttons is set to the value of the bgcolor parameter."

To answer your query: no, only if butbgcolor is not set.

I would be happy to clarify functionality if it is not clear from the parameter descriptions :-)

**Comment by mfo13** [comment]
Oh, now I understand. I didn't realize for that. You are correct the config tool must follow the docs of Animcube. I'll work on that.

**Comment by mfo13** [comment]
I think this issue is now solved. Please make some tests.

**Comment by bcube2** [comment]
Nicely done, thank you.
